INSERT into familias(nombre, descripcion, foto) values ("Virus Busters", "Familia a la que pertenecen generalmente Digimon sagrados o angelicales, o aquellos que residan en áreas sagradas", "storage/iconos/familias/vb.png");
INSERT into familias(nombre, descripcion, foto) values ("Dark Area", "Familia a la que pertenecen generalmente Digimon malvados o apocalipticos, o aquellos que residan en la Dark Area", "storage/iconos/familias/da.png");
INSERT into familias(nombre, descripcion, foto) values ("Deep Savers", "Familia a la que pertenecen generalmente Digimon aquáticos o polares, o aquellos que residan en zonas marinas", "storage/iconos/familias/ds.png");
INSERT into familias(nombre, descripcion, foto) values ("Dragon's Roar", "Familia a la que pertenecen generalmente Digimon dragones o con rasgos dragontinos, o aquellos que residan en áreas volcánicas", "storage/iconos/familias/dr.png");
INSERT into familias(nombre, descripcion, foto) values ("Jungle Troopers", "Familia a la que pertenecen generalmente Digimon insectos o vegetales, o aquellos que residan en áreas tropicales", "storage/iconos/familias/jt.png");
INSERT into familias(nombre, descripcion, foto) values ("Metal Empire", "Familia a la que pertenecen generalmente Digimon mecánicos o mutantes, o aquellos que residan en áreas urbanas o industriales", "storage/iconos/familias/me.png");
INSERT into familias(nombre, descripcion, foto) values ("Nature Spirits", "Familia a la que pertenecen generalmente Digimon asociables a animales o similares a monstruos, o aquellos que residan en áreas similares a un desierto", "storage/iconos/familias/nsp.png");
INSERT into familias(nombre, descripcion, foto) values ("Nightmare Soldiers", "Familia a la que pertenecen generalmente Digimon asociables a demonios o no-muertos, o aquellos que residan en zonas encantadas o malditas", "storage/iconos/familias/nsos.png");
INSERT into familias(nombre, descripcion, foto) values ("Wind Guardians", "Familia a la que pertenecen generalmente Digimon alados o voladores, o aquellos que residan en áreas similares a praderas o elevadas", "storage/iconos/familias/wg.png");
INSERT into familias(nombre, descripcion, foto) values ("Unknown", "Familia a la que pertenecen generalmente Digimon mutantes incategorizables.", "storage/iconos/familias/uk.png");
INSERT into familias(nombre, descripcion, foto) values ("TBD", "Familia a la que pertenecen generalmente Digimon que, por el motivo que sea, no son asignables a ninguna otra familia.", "storage/iconos/familias/tbd.png");

INSERT into proscontras (pro_contra, descripcion) values (0, "El daño de su F3 es muy alto");
INSERT into proscontras (pro_contra, descripcion) values (0, "Buena habilidad de AoE (Área de Efecto)");
INSERT into proscontras (pro_contra, descripcion) values (0, "Siendo Vacuna/Luz, tiene doble ventaja contra los enemigos más comunes.");
INSERT into proscontras (pro_contra, descripcion) values (0, "Fácil y rápido de digievolucionar, agregando a sus capacidades de supervivencia");
INSERT into proscontras (pro_contra, descripcion) values (0, "Uno de los pocos Digimon con cuatro habilidades");
INSERT into proscontras (pro_contra, descripcion) values (0, "Posee ASB (Advance Skill Breaking) en todas sus habilidades.");
INSERT into proscontras (pro_contra, descripcion) values (1, "Alto consumo de maná (Digisoul)");
INSERT into proscontras (pro_contra, descripcion) values (1, "Exclusivo de lootbox (Caja de botín) de pago con 1% de probabilidad de obtención");
INSERT into proscontras (pro_contra, descripcion) values (1, "Exclusivo de un evento temporal de la Arena");
INSERT into proscontras (pro_contra, descripcion) values (1, "Salud mediocre/mala para su rango");
INSERT into proscontras (pro_contra, descripcion) values (1, "Ataque mediocre/malo para su rango");
INSERT into proscontras (pro_contra, descripcion) values (1, "Animaciones de habilidades lentas");
INSERT into proscontras (pro_contra, descripcion) values (0, "Animaciones de habilidades rápidas");
INSERT into proscontras (pro_contra, descripcion) values (0, "Efecto especial en una o varias habilidades");
INSERT into proscontras (pro_contra, descripcion) values (0, "Su mejor habilidad puede ser reiniciada con el Reset Deck, saltándose el largo tiempo de recarga");
INSERT into proscontras (pro_contra, descripcion) values (0, "Alta probabilidad de críticos base");
INSERT into proscontras (pro_contra, descripcion) values (0, "Forma parte de un deck poderoso, por lo cual su obtención es más atractiva");
INSERT into proscontras (pro_contra, descripcion) values (1, "Exclusivo de las lootbox (cajas de botín) ocasionales y caras del juego, dificultando mucho su obtención");
INSERT into proscontras (pro_contra, descripcion) values (1, "Su mejor habilidad, incluso dedicandole todos los puntos, no puede llegar a nivel 25, limitando su potencial");
INSERT into proscontras (pro_contra, descripcion) values (1, "El/los efecto/s especial/es no mejora/n conforme se sube de nivel la habilidad a la que está asociado cada uno");
INSERT into proscontras (pro_contra, descripcion) values (0, "Salud alta o muy alta para su rango");
INSERT into proscontras (pro_contra, descripcion) values (0, "Ataque alto o muy alto para su rango");
INSERT into proscontras (pro_contra, descripcion) values (0, "Defensa alta o muy alta para su rango");
INSERT into proscontras (pro_contra, descripcion) values (1, "Alto tiempo de recarga para sus habilidades");
INSERT into proscontras (pro_contra, descripcion) values (0, "Debido a sus familias, obtiene un incremento significativo de daño en días concretos gracias al Shadow Labyrinth");
INSERT into proscontras (pro_contra, descripcion) values (0, "Alta probabilidad de Evasión");
INSERT into proscontras (pro_contra, descripcion) values (1, "Exclusivo de lootbox (caja de botín) con un 0,1% de probabilidad");
INSERT into proscontras (pro_contra, descripcion) values (1, "Requiere varias líneas desbloqueadas completamente de Digimon X para poder evolucionar");
INSERT into proscontras (pro_contra, descripcion) values (1, "Posee la habilidad con el mayor tiempo de recarga del juego (6 minutos para su All-Delete)");
INSERT into proscontras (pro_contra, descripcion) values (1, "Su mejor habilidad no puede ser reiniciada con el Reset Deck");
INSERT into proscontras (pro_contra, descripcion) values (1, "Las misiones requeridas para su desbloqueo total o parcial son largas y molestas de completar");


INSERT into digimon (nombre, descripcion, rango, nivel, utilidad, atributo, tipo, health_points, digisoul_points, attack, attack_speed, critical_chance, hitrate, defense, evasion, skill1, skill1_base, skill1_increment, skill2, skill2_base, skill2_increment, skill3, skill3_base, skill3_increment, skill4, skill4_base, skill4_increment) values ("Susanoomon (Shin)", "Como se cuenta en las leyendas orientales, es el dios que gobierna sobre la destrucción y la regeneración. Se cuenta que, cuando el sistema de red cae en el caos, borrará el mismo y creará uno nuevo.", "SSS+", "Jogress", "DPS", "Vacuna", "Luz", 16687, 5327, 5876, 2.2, 24.87, 510, 537, 29.7, "Juicio Divino", 11817, 294, "Trueno del Cielo", 27792, 609, "Espada de los Cielos", 126572, 4598, "Zero-Arms-Orochi", 27122, 985);
INSERT into digimon (nombre, descripcion, rango, nivel, utilidad, atributo, tipo, health_points, digisoul_points, attack, attack_speed, critical_chance, hitrate, defense, evasion, skill1, skill1_base, skill1_increment, skill2, skill2_base, skill2_increment, skill3, skill3_base, skill3_increment) values ("Omegamon X", "Omegamon X (Omnimon X en España) es la versión mejorada de Omegamon, tras obtener el anticuerpo X de manos de un moribundo Alphamon Ouryuken tras su sacrificio para derrotar a Dexmon durante el asalto a la base de Yggdrasil. Al ser consciente de las malas decisiones de su dios, Omegamon X fuerza el reinicio del mundo digital destruyendo el avatar de Yggdrasil con su All Delete.", "SSS+", "Jogress X", "Tank/DPS", "Vacuna", "Luz", 19578, 5583, 7865, 2.4, 27.25, 419, 595, 45.1, "Cañón Supremo", 23080, 506, "Espada Trascendente", 34620, 759, "All Delete", 131362, 1683);

INSERT into digimon_familia(digimon_id, familia_id) values (1, 1);
INSERT into digimon_familia(digimon_id, familia_id) values (1, 8);
INSERT into digimon_familia(digimon_id, familia_id) values (2, 1);
INSERT into digimon_familia(digimon_id, familia_id) values (2, 6);
INSERT into digimon_familia(digimon_id, familia_id) values (2, 9);

INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,1);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,2);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,3);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,4);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,5);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,6);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,7);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,9);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,10);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,11);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (1,12);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,2);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,3);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,17);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,25);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,16);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,26);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,27);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,31);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,29);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,30);
INSERT into digimon_proscontra(digimon_id, procontra_id) values (2,28);
